new Promise(function (resolve, reject) {
    setTimeout(() => {
        throw new Error("Whoops!");
    }, 1000);
}).catch(alert);
// خیر اجرا نمیشه

//  پشته زمانی که برنامه اجرا می شود اطلاعات در قالب ساختار داده ای
//  پشته ذخیره می شوند،زمانی که متدی فراخوانی می شود،اطلاعات در پشته ذخیره می شن تا زمانی که متد برگرده. از اونجایی که متد ها غالبا 
//  متد های دیگر رو فراخوانی می کنن بنابراین پشته همین طور رشد میکنه،تا زمانی که متد ها بازگشت داده شو
// ند یا به اصطلاح برنامه به پایان برسه. زمانی که یک خطایی به پشته ای از فراخوانی های تابع که هنوز بازگشت نداده شده ارسال میشه
// ، چون هنوز اطلاعات داخل پشته بازگشت داده نشده (تا زمانی که خطا شناسایی و مدیریت بشه)برنامه به طور کلی متوقف می شه.